# Generated by Django 2.2.10 on 2022-05-13 17:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields
import myapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('displayYearbook', models.BooleanField(default=False)),
                ('deadline', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='GenQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('department', models.CharField(choices=[('chemical', 'chemical'), ('civil', 'civil'), ('cse', 'computer science'), ('ee', 'electrical'), ('maths', 'mathematics'), ('mech', 'mechanical'), ('physics', 'engineering physics'), ('textile', 'textile engineering'), ('dbeb', 'biotechnology'), ('all', 'all')], max_length=100)),
                ('DP', models.ImageField(blank=True, default='DP/anonymous.jpg', upload_to='DP')),
                ('genPic1', models.ImageField(blank=True, upload_to=myapp.models.user_directory_path)),
                ('genPic2', models.ImageField(blank=True, upload_to=myapp.models.user_directory_path)),
                ('phone', models.CharField(blank=True, max_length=10)),
                ('email', models.CharField(blank=True, max_length=100)),
                ('oneliner', models.CharField(blank=True, max_length=100)),
                ('future', models.CharField(blank=True, max_length=100)),
                ('AnswersAboutMyself', jsonfield.fields.JSONField(blank=True, default=dict)),
                ('VotesIHaveGiven', jsonfield.fields.JSONField(blank=True, default=dict)),
                ('CommentsIWrite', jsonfield.fields.JSONField(blank=True, default=list)),
                ('CommentsIGet', jsonfield.fields.JSONField(blank=True, default=list)),
                ('WordCloud', models.ImageField(blank=True, upload_to='wordcloud')),
                ('closeFriends', jsonfield.fields.JSONField(blank=True, default=dict)),
                ('closeFriendsPic', models.ImageField(blank=True, upload_to=myapp.models.user_directory_path)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poll', models.CharField(max_length=200)),
                ('department', models.CharField(choices=[('chemical', 'chemical'), ('civil', 'civil'), ('cse', 'computer science'), ('ee', 'electrical'), ('maths', 'mathematics'), ('mech', 'mechanical'), ('physics', 'engineering physics'), ('textile', 'textile engineering'), ('dbeb', 'biotechnology'), ('all', 'all')], max_length=200)),
                ('votes', jsonfield.fields.JSONField(blank=True, default=dict)),
            ],
            options={
                'unique_together': {('poll', 'department')},
            },
        ),
        migrations.CreateModel(
            name='Adjective',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adjective', models.CharField(choices=[('optimistic', 'optimistic'), ('kanjoos', 'kanjoos'), ('genius', 'genius'), ('gym-freak', 'gym-freak'), ('tharki', 'tharki'), ('maggu', 'maggu'), ('helpful', 'helpful'), ('cry-baby', 'cry-baby'), ('hard-working', 'hard-working'), ('show-off', 'show-off'), ('pakau', 'pakau'), ('foodie', 'foodie'), ('gossiper', 'gossiper'), ('poltu-baaz', 'poltu-baaz'), ('chep', 'chep'), ('comedy-king', 'comedy-king')], max_length=100)),
                ('byWhom', models.ManyToManyField(related_name='AdjectivesIGive', to='myapp.Student')),
                ('forWhom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AdjectivesIGet', to='myapp.Student')),
            ],
        ),
    ]
