# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-05 11:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='genPics')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('DP', models.ImageField(upload_to='DP')),
                ('phone', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=100)),
                ('oneliner', models.CharField(max_length=100)),
                ('AnswersAboutMyself', jsonfield.fields.JSONField()),
                ('VotesIHaveGiven', jsonfield.fields.JSONField()),
                ('CommentsIWrite', jsonfield.fields.JSONField()),
                ('CommensIGet', jsonfield.fields.JSONField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='imagemodel',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Student'),
        ),
    ]
