# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-10 13:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20180407_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='department',
            field=models.CharField(choices=[('tesi', 'tesi'), ('AP', 'AP')], max_length=100),
        ),
    ]
