# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-05 13:23
from __future__ import unicode_literals

from django.db import migrations, models
import myapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20180405_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemodel',
            name='image',
            field=models.ImageField(upload_to=myapp.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='student',
            name='DP',
            field=models.ImageField(upload_to='media/DP'),
        ),
    ]
