# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-05 20:00
from __future__ import unicode_literals

from django.db import migrations, models
import myapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20180405_1853'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagemodel',
            name='student',
        ),
        migrations.AddField(
            model_name='student',
            name='genPic1',
            field=models.ImageField(blank=True, upload_to=myapp.models.user_directory_path),
        ),
        migrations.AddField(
            model_name='student',
            name='genPic2',
            field=models.ImageField(blank=True, upload_to=myapp.models.user_directory_path),
        ),
        migrations.DeleteModel(
            name='ImageModel',
        ),
    ]
