# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-11 14:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20180411_1554'),
        ('myapp', '0005_auto_20180410_2142'),
    ]

    operations = [
    ]
