# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-05 20:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20180406_0130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='DP',
            field=models.ImageField(blank=True, upload_to='media/DP'),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
