# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-15 16:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_merge_20180411_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='department',
            field=models.CharField(choices=[('biotech', 'biotech'), ('chemical', 'chemical'), ('civil', 'civil'), ('cse', 'cse'), ('ee', 'ee'), ('maths', 'maths'), ('mech', 'mech'), ('physics', 'physics'), ('textile', 'textile'), ('all', 'all')], max_length=200),
        ),
        migrations.AlterField(
            model_name='student',
            name='department',
            field=models.CharField(choices=[('biotech', 'biotech'), ('chemical', 'chemical'), ('civil', 'civil'), ('cse', 'cse'), ('ee', 'ee'), ('maths', 'maths'), ('mech', 'mech'), ('physics', 'physics'), ('textile', 'textile'), ('all', 'all')], max_length=100),
        ),
    ]
