# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-06 14:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20180406_0132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='oneliner',
        ),
    ]
