# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-06 14:08
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_remove_poll_oneliner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='votes',
            field=jsonfield.fields.JSONField(blank=True),
        ),
    ]
