# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-06 16:26
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_auto_20180406_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='votes',
            field=jsonfield.fields.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='student',
            name='AnswersAboutMyself',
            field=jsonfield.fields.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='student',
            name='CommensIGet',
            field=jsonfield.fields.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='student',
            name='CommentsIWrite',
            field=jsonfield.fields.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='student',
            name='VotesIHaveGiven',
            field=jsonfield.fields.JSONField(blank=True, default=dict),
        ),
    ]
