# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-06 18:32
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_auto_20180406_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='CommentsIGet',
            field=jsonfield.fields.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='student',
            name='CommentsIWrite',
            field=jsonfield.fields.JSONField(blank=True, default=list),
        ),
    ]
