# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-07 07:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_auto_20180407_0002'),
        ('myapp', '0011_auto_20180406_2156'),
    ]

    operations = [
    ]
