# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-07 07:37
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_merge_20180407_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='CommentsIWrite',
            field=jsonfield.fields.JSONField(blank=True, default=list),
        ),
    ]
